Repository kowainik/colourista, pull requests merged in 2020-02, with the labels that each got.

#4 [#1] Cleanup repo
  .github/workflows/ci.yml
  .travis.yml
  colourista.cabal
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack-8.6.5.yaml
  stack.yaml
Labels: refactoring

#9 [#2] Bring pure interface functions
  colourista.cabal
  src/Colourista.hs
  src/Colourista/Pure.hs
Labels: enhancement

#11 [#10] Make pure code functions polymorphic on `IsString`
  colourista.cabal
  src/Colourista/Pure.hs
Labels: enhancement

#12 [#6] Add pure background functions
  src/Colourista/Pure.hs
Labels: enhancement

#13 [#5] Bring IO formatting functions
  .travis.yml
  colourista.cabal
  src/Colourista/IO.hs
Labels: enhancement

#14 [#8] Implement a function for formatting pure strings with multiple formatters
  src/Colourista.hs
  src/Colourista/IO.hs
  src/Colourista/Pure.hs
Labels: enhancement

#15 [#3] Write README
  README.md
  src/Colourista.hs
Labels: documentation
