Repository kowainik/colourista, pull requests merged in 2021-04, with the labels that each got.

#56 [#41] Add some tests
  .gitignore
  colourista.cabal
  test/Spec.hs
  test/Test/Colourista.hs
Labels: tests

#57 [#55] Support GHC-9.0
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  colourista.cabal
  stack.yaml
Labels: CI, library

#58 Prepare release 0.1.0.1
  CHANGELOG.md
  README.md
  colourista.cabal
  src/Colourista.hs
  src/Colourista/IO.hs
  src/Colourista/Pure.hs
  src/Colourista/Short.hs
Labels: documentation
